# Generated by Django 4.2.5 on 2023-09-23 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0009_alter_alumno_pepe'),
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.examen')),
            ],
        ),
    ]
